name: run_2_future_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutterflow_ui: ^0.2.0+1
  http: ^0.13.6
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/"
